### ISSUE TITLE
deploy splash.jar to maven central or own repository

### ISSUE THREAD

**Issue by berlinguyinca** [berlinguyinca/spectra-hash#13]
we require to deploy the splash reference api to a maven repository

**Comment by tomas-pluskal** [comment]
To deploy to maven central, you need to go through the Sonatype repo (https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide). It is quite a painful process, and you will also need to generate javadoc jars etc. I recommend to just deploy to your own repository, as long as it is stable.

**Comment by tomas-pluskal** [comment]
I guess this can be closed now
