### ISSUE TITLE
Error on request to REST API

### ISSUE THREAD

**Issue by stuchalk** [berlinguyinca/spectra-hash#16]
If I send JSON to http://splash.fiehnlab.ucdavis.edu/splash/it with the Content-Type as 'application/json;charset=UTF-8' I get the following error (using CakePHP's httpSocket)

`object(HttpSocketResponse) {
	body => '{"timestamp":1453461906523,"status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported","path":"/splash/it"}'
	headers => array(
		'Server' => 'nginx/1.4.6 (Ubuntu)',
		'Date' => 'Fri, 22 Jan 2016 11:25:06 GMT',
		'Content-Type' => 'application/json;charset=UTF-8',
		'Transfer-Encoding' => 'chunked',
		'Connection' => 'close',
		'Set-Cookie' => 'OPENSHIFT_splash_web_SERVERID=10.1.2.6:80; path=/; HttpOnly'
	)
	cookies => array(
		'OPENSHIFT_splash_web_SERVERID' => array(
			'value' => '10.1.2.6:80',
			'path' => '/',
			'httponly' => true
		)
	)
	httpVersion => 'HTTP/1.1'
	code => '415'
	reasonPhrase => 'Unsupported Media Type'
	raw => 'HTTP/1.1 415 Unsupported Media Type`
If I remove the 'charset=UTF-8' it works fine...

**Comment by benn7** [comment]
Thank you for reporting this issue. JSON strings are encoded in UTF-8 by default, you don't need to explicitly add 'charset=UTF-8'. When you send 'application/json' header, it will use UTF-8.

**Comment by stuchalk** [comment]
OK, I understand.  Still, I think it should ignore the charset statement rather than throwing an error...

**Comment by benn7** [comment]
Looking at the error code:
415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type **'application/x-www-form-urlencoded;charset=UTF-8'** not supported

It looks like your request was not sent with 'application/json', even though your header decleraed 'application/json'. I'm not familiar with cakePHP HttpSocket, but I would look to make sure *Content-Type application/json* is being sent through.

**Comment by stuchalk** [comment]
OK, I will hard code it.  Thanks
