### ISSUE TITLE
Maven repository is unavailable

### ISSUE THREAD

**Issue by nilshoffmann** [berlinguyinca/spectra-hash#34]
Hi,
trying to retrieve release versions of SPLASH currently fails, whenever Maven accesses the following URL:
http://gose.fiehnlab.ucdavis.edu:55000/content/groups/public

to retrieve the following artifact:
Downloading: http://gose.fiehnlab.ucdavis.edu:55000/content/groups/public/edu/ucdavis/fiehnlab/splash/core/1.8/core-1.8.pom

Looks like the repository is either down or unavailable.

This causes downstream build failures for MSDK, whenever the Maven artifact cache is cleared: https://github.com/msdk/msdk/issues/247

**Comment by ssmehta** [comment]
Hi Nils, the repository appears to be running fine on my end and we haven't had any downtime lately according to my logs.

You are not able to view the pom file you linked?  What error do you receive?

**Comment by nilshoffmann** [comment]
Hi Sajjan,
thanks for lookin into this.  I receive a time-out when attempting to either access the pom file via the browser or via Maven. I can conform that the repository is available from the outside, but not from within our institution's network due to the non-standard port number being blocked.
Any chance of providing a transparent proxy for the repository on port 80? Or, as an alternative, pushing the artifacts to Maven central?

**Comment by nilshoffmann** [comment]
Access works after adapting firewall rules.
