### ISSUE TITLE
discuss where we can document that Wikidata now supports the SPLASH

### ISSUE THREAD

**Issue by egonw** [berlinguyinca/spectra-hash#36]
Hi all,

after some discussions on Twitter, I took the jump last week and proposed the SPLASH as property in Wikidata, which you can currently see in action for caffeine: https://www.wikidata.org/wiki/Q60235 (scroll down the page or Ctrl^F for SPLASH). I am talking to people to release CCZero-licensed InChIKey<>SPLASH tuples, allowing me to import last combinations to populate Wikidata quickly. BTW, it currently links out to MONA.

Question is, do we want to document this feature somewhere here or on the official website?

**Comment by egonw** [comment]
PS, the growing list of SPLASH (well, n=3 at the time of writing) can be retrieved with: http://tinyurl.com/ybcuajpc

![image](https://user-images.githubusercontent.com/26721/37601537-8cc22262-2b8a-11e8-8184-a27d330287e7.png)

**Comment by berlinguyinca** [comment]
Feel free to submit a pull request to get it added to http://splash.fiehnlab.ucdavis.edu/

**Comment by egonw** [comment]
Hi all, progress on getting SPLASHes into Wikidata: http://chem-bla-ics.blogspot.nl/2018/03/splashes-in-wikidata.html

**Comment by berlinguyinca** [comment]
@egonw any update on the pull request, if you would like to have it added?
