### ISSUE TITLE
what is the latest regular expression?

### ISSUE THREAD

**Issue by egonw** [berlinguyinca/spectra-hash#37]
I picked up the "splash\d[A-Z-a-z0-9]-[A-Za-z0-9]+-[A-Za-z0-9]+" regular expression somewhere, not noting this is the old syntax... where can I find the latest regex?

**Comment by ssmehta** [comment]
Here is the regex I'm using in MoNA, it's a bit more strict:

`^(splash[0-9]{2}-[a-z0-9]{4}-[0-9]{10}-[a-z0-9]{20})$`
