### ISSUE TITLE
R implementation (and maybe others?) still doing "old" histograms

### ISSUE THREAD

**Issue by schymane** [berlinguyinca/spectra-hash#7]
PR100026 is now splash10-0z00000000-3ed37a8875b091fa7b34.
Histogram is now 0-z and second block.

**Comment by sneumann** [comment]
R implementation in sync with manuscript again since 975c3615639072669dc35b182155a50ee714cc8c,
unit tests ensure validation against test set. 
From splashR implementation issue can be closed methinks.

**Comment by sneumann** [comment]
R implementation is in sync with Java SPLASH-1.6 as of c1936f54c04ec76aa6af34d477e8ece84fb71cc2
